experiment:
    project: "unilip"
    name: "unilip_stage2_imagenet"
    output_dir: "checkpoints/unilip_stage2_imagenet"
    max_train_examples: 1_281_167    # ImageNet训练集大小
    save_every: 5_000
    eval_every: 5_000
    generate_every: 1_000
    log_every: 50
    log_grad_norm_every: 500
    resume: True
    init_weight: ""


model:
    name: DC_AE_ViT_Unified
    embed_dim: 32
    patch_size: 14
    mllm_path: "/mnt/tidal-alsh01/dataset/zeus/lihongxiang/models/InternVL3-1B"
    dc_ae_path: "/mnt/tidal-alsh01/dataset/zeus/lihongxiang/models/dc-ae-f32c32-sana-1.1-diffusers"
    # Stage2 specific: load stage1 checkpoint, unfreeze encoder
    stage1_ckpt: unilip_stage1_imagenet/checkpoint-100000/ema_model/pytorch_model.bin
    freeze_encoder: False
    output_distill_feat: True
    disable_drop_path: True
    use_gradient_checkpoint: False
    vq_model:
        quantize_mode: vae


losses:
    name: ReconstructionLoss_Unified
    discriminator_start: 30_000
    quantizer_weight: 1.0
    discriminator_factor: 1.0
    discriminator_weight: 0.1
    perceptual_loss: "lpips-convnext_s-1.0-0.1"
    perceptual_weight: 1.1
    # Enable distillation in stage2
    distill_loss: /mnt/tidal-alsh01/dataset/zeus/lihongxiang/models/InternVL3-1B
    distill_weight: 1.0
    reconstruction_loss: "l2"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.001
    kl_weight: 0.0
    logvar_init: 0.0

dataset:
    params:
        train_shards_path_or_url: "/mnt/tidal-alsh01/dataset/zeus/lihongxiang/unified_model/VGT/tokenizer/data/dataset/train/imagenet-train-{000000..000320}.tar"
        eval_shards_path_or_url: "/mnt/tidal-alsh01/dataset/zeus/lihongxiang/unified_model/VGT/tokenizer/data/dataset/val/imagenet-val-{000000..000049}.tar"
        num_workers_per_gpu: 12
        dataset_with_class_label: True
        dataset_with_text_label: False
    preprocessing:
        resize_shorter_edge: 224
        crop_size: 224
        random_crop: True
        random_flip: True
        normalize_mean: [0.485, 0.456, 0.406]
        normalize_std: [0.229, 0.224, 0.225]
        imagenet_norm: True


optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        discriminator_learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.999
        weight_decay: 1e-4
        use_encoder_lr_scale: True
        encoder_lr_scale: 0.1

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 3_000
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 32
    mixed_precision: "bf16"
    enable_tf32: True
    enable_wandb: True
    wandb_api_key: "3ed65eb52edcc37a5e278a82dd874b44d4ffadb7"
    ddp_find_unused_parameters: False
    use_ema: True
    seed: 42
    max_train_steps: 80_000
    num_generated_images: 8
    max_grad_norm: 1.0

